"""New Migration

Revision ID: 68d07af0f06a
Revises: 0ca0f24a6ef0
Create Date: 2022-01-19 16:34:43.016710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d07af0f06a'
down_revision = '0ca0f24a6ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
